- src/test_c2s_srv.c
- src/test_s2c_srv.c
Adds two alarm() calls which will act as watchdog timers for the c2s process to prevent runaway packet captures.
> Make sure every fork()ed subprocess has a watchdog timer.

- src/test_meta_srv.c
Adds two new variables to the metalog: "websockets" and "tls". The possible
values for both variables are "true" or "false" depending on whether the test
ran over websockets and/or TLS, respectively.
> Add TLS and WebSockets information to metalog

- src/logging.h
- src/network.c
- src/test_meta_srv.c
- src/web100srv.c
- src/web100srv_unit_tests.c
- src/websocket.c
The bug where the server would freeze sometimes. (accept() was getting interrupted)
The bug where SSL sockets would cause the META test to fail.
The bug where the OS name got cut off at 32 chars, almost certainly clobbering a pointer which was stored later in the same struct.
readn_any's error handling, because SSL_read can return an error which literally means "please call SSL_read".
run_meta_test_srv's error handling now correctly logs the error
> Fixed: server freeze and other SSL, error handling, and buffer bugs

- src/network.c
- src/node_tests/ndt_client.js
SSL_shutdown() is not like close(), it instead causes a shutdown signal to be transmitted to the client.
Remove SSL_shutdown from codepaths that mean close() in other contexts.
> SSL_shutdown() is not like close()

- src/network.c
- src/test_s2c_srv.c
- src/web100srv_unit_tests.c
raw_write is unsafe in the presence of websockets, and it relies too heavily on write() and SSL_write having the same error semantics. Use writen_any instead.
> Change raw_write usage to writen_any.

- src/test_meta_srv.c
- src/testoptions.c
- src/testoptions.h
The meta values for tls and websockets are now saved whether or not the client actually runs the meta test.
Required a little more code movement than I thought it would, and it gave me a chance to fix an egregiously bad implementation of a linked list as part of moving code around.
> Save the tls and websocket keys unconditionally.

- src/test_c2s_srv.c
This change addresses a regression observed for web100clt during the c2s test.
In particular, before this change, web100clt can block while writing after the
c2s server stopped reading. This causes the rest of the test to fail.
The server implementation in NDT 3.7.0 attempted to read longer than the client
wrote. The change in NDT 4.0.0 made the c2s read loop strictly conditional on
testDuration. This resulted in a race condition with the client.
> Extend c2s server read loop by 1 second.

- src/network.h
- src/testoptions.h
- src/websocket.h
web100clt can't include testoptions.h, so move some constants around.
> Fix includes for web100clt

- src/test_c2s_srv.c
Adds a second of reading after a c2s test is done to allow old brittle clients to clear out their queues.
> Adds a second of reading after a c2s test

- src/network.c
Change the loop that calls read() to error out when select() returns an error and errno is not EINTR.
> Change the loop that calls read() to error out when it should

- src/test_c2s_srv.c
If packet capture fails to start for whatever reason, then the whole client gets hung in a read.  When enough clients are hung, then all incoming clients get queued, and the queue never gets any smaller.
This adds a `select()` in front of the `read()` to ensure that the pipe becomes readable within a second. Thus, if the packet trace is unable to start, the test can still proceed without it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/51)
> No more freezing if pcap process goes wrong

- src/test_c2s_srv.c
- src/web100srv.c
- src/web100srv_unit_tests.c
Three small bugfixes, one of which was causing real issues for MLab servers in developing nations.
* A one-line compiler warning fix for test_c2s.
* Fixing watchdog timer issues in web100srv.  (The server bug)
* Making end-to-end unit tests less flaky by no longer just assuming that every port in the range [1024, 31024) is fine for the server to take as its own.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/52)
> Three small bugfixes

- HTML5-frontend/Makefile.am
Building NDT fails in HTML-frontend/ because the Makefile was referencing an older version of the jQuery library which no longer exists in that directory.  Updates the Makefile to reference the version currently installed there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/53)
> Update HTML-frontend Makefile to reference new version of jquery.

- HTML5-frontend/ndt-browser-client.js
- HTML5-frontend/ndt-library.js
- HTML5-frontend/script.js
- HTML5-frontend/style.css
- HTML5-frontend/widget.html
Per feedback contained in #49 this PR splits the changes in that PR into a more manageable PR.  This first PR contains and only contains the changes needed to separate the backend functionality from the `script.js` file into an `ndt-library.js` file.  When moving that functionality to the `ndt-library.js` file, it needs to be removed from the `script.js` file and then minimal changes to make sure the application still works.
The idea is to ease how an implementer might include an NDT js library onto their website and by including only the necessary js, an implementer could create their own frontend using the NDT js library.  
As the current implementation would require a website to include [five different scripts](https://github.com/m-lab/m-lab.github.io/pull/76/files#diff-56ff23ff64480499 …
> Separating Frontend and Backend Functionality in NDT HTML5 Client - Part 1

- HTML5-frontend/ndt-library.js
- HTML5-frontend/script.js
This PR's main focus are fixes to the js to ensure a clean JSLint on the HTML5-frontend/script.js and HTML5-frontend/ndt-library.js files.
The JSLint fixes entailed:
- a lot of spacing changes in statements,
- a lot of moving around of methods
- some minor logic changes as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/61)
> JSLint fixes for separation of Frontend & Backend NDT

- src/web100-pcap.c
- src/web100srv.c
Adds the watchdog timer as the very first thing, and eliminates the "return"
from the error paths which is never the right thing and is potentially
disastrous.
Also, eliminates a string from a log line which frequently ended up being a
pointer to memory that did not contain a string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/65)
> Watchdog timer, error path bugfixes, and a logging cleanup.

- src/network.c
- src/network.h
- src/test_c2s_srv.c
- src/test_s2c_srv.c
- src/test_sfw_srv.c
- src/testoptions.c
- src/testoptions.h
- src/web100-pcap.c
- src/web100srv.c
Adds 5 minute timeouts to the control socket, the s2c sockets, and the c2s
socket. Also removes the vestigial `alarm()` and SIGALRM handler in the s2c
test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/71)
> Fix hanging child process problem.

- HTML5-frontend/ndt-wrapper.js
- HTML5-frontend/script.js
- HTML5-frontend/widget.html
The HTML interface has been reporting a "Jitter" metric on the main NDT test results page.  This metric is the value of MaxRTT - MinRTT.  While in some technical sense this may be a measure of jitter by some definition, this is almost certainly not the same sense of the term jitter that the vast majority of people using the NDT test are going to want or understand.  This PR removes jitter from the results page, as well as just getting rid of the functions and variables that calculated and defined it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/48)
> Removes 'Jitter' metric from HTML interface

- HTML5-frontend/script.js
- HTML5-frontend/style.css
- HTML5-frontend/widget.html
M-Lab hasn't supported the Java NDT test for a long time. We no longer even sign the Java applet that is deployed with NDT. However, the webserver built into NDT still serves a page which gives the user the option to run a test using either the Java applet or the WebSocket client, additionally adding a scary red warning that the WebSocket client is "beta".
This PR removes both the Java and WebSocket buttons, leaving on a single "Start Test" button. If the user's browser doesn't support WebSockets a red warning message is displayed and the "Start Test" button is effectively disabled.
I'm sure that a vanishingly small number of people or things run NDT tests directly from the NDT sliver (e.g., [http://ndt.iupui.mlab1.den01.measurement-lab.org:7123](http://ndt.iupui.mlab1.den01.measurement-la …
> Removes Java option from HTML interface served by NDT sliver

- .travis.yml
Try again - first PR was to master instead of to dev branch.
Adds a travis integration for NDT build.
Currently uses a temporary builder container. Will update this once we have standardized on mlab-oti container registry, probably in a couple days.
Still need to hammer out (before pushing to master) a plan for whether or how this might be pushed upstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/80)
> Travis for ndt

- src/web100srv_unit_tests.c
Removes the logfile after the unit tests run
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/88)
> Remove logfile after test

- src/Makefile.am
Since we are probably never going to build NDT again on a machine with a web100-patched kernel, remove web100srv unit testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/89)
> Removes web100srv unit testing from builds

- .travis.yml
This change addresses build failures discovered in https://github.com/m-lab/ndt/pull/96
The original docker build and run of the ndt_build_and_test.sh script depends on `dev` branches in both the m-lab/builder and m-lab/ndt-support repositories.
This change removes the dependency on the builder repo (where the dev branch had been deleted) in favor of the pre-built canonical builder docker image, `measurementlab/builder:production-1.0`.
As well, this change uses the m-lab/ndt-support master repo and replaces the old ndt submodule reference with a local reference to the current TRAVIS_COMMIT.
The result of these changes is that changes to m-lab/ndt will be tested by building the m-lab/ndt-support package using the `measurementlab/builder:production-1.0` environment.
The build and test steps …
> Use canonical build image and local version of NDT

- HTML5-frontend/script.js
- HTML5-frontend/style.css
- HTML5-frontend/widget.html
* Removes Java and WebSocket test buttons from HTML interface, such that all tests are WebSocket (if available) and only a 'Start Test' button.
* Eliminate a useless function, don't even append the Java applet to the DOM, and don't initialize the test if WebSocket support isn't detected.
* Eliminates an unused variable, eliminates a useless function, and fixes some typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/ndt/96)
> Removes Java option from HTML interface served by NDT sliver (#73)

- src/test_s2c_srv.c
This change includes a fix for segfaults in the NDT server for some clients that send incorrect message headers.
Using pcap traces we've observed that some clients send a message header hex: 05 00 07, followed by a message str: `{"msg": "81034.0"}`. The header sends a length of 7 but the actual message is 17 characters long. As a result, the `json_read_map_value` fails. However, the original logic did not check the return value (`NULL`) which resulted in a SEGV during `strlcpy`.
This change checks the return value and assigns an invalid default value `-1` for the client-reported speed instead of reporting an error to the client because we believe these clients are deployed in a manner that they repeat tests after an error.
---
This change is [<img …
>  Prevent SEGV by checking value from json_read_map_value
